### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by Fema81** [mchizk1/ShinyFruit#1]
Hi, some troubles when running
devtools::install_github("mchizk1/ShinyFruit", build_vignettes = T) both on RStudio desktop swell as RStudio Cloud. I working on Mac Air  (m1) see below

> devtools::install_github("mchizk1/ShinyFruit", build_vignettes = T)
Downloading GitHub repo mchizk1/ShinyFruit@HEAD
Installing 1 packages: imager
Installing package into ‘/cloud/lib/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'http://rspm/default/__linux__/focal/latest/src/contrib/imager_0.42.13.tar.gz'
Content type 'application/x-gzip' length 4817758 bytes (4.6 MB)
==================================================
downloaded 4.6 MB

* installing *source* package ‘imager’ ...
** package ‘imager’ successfully unpacked and MD5 sums checked
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++14 accepts -g... yes
checking how to run the C++ preprocessor... g++ -std=gnu++14 -E
checking for X... libraries , headers 
checking for XOpenDisplay in -lX11... yes
X11 library found.
configure: Checking if FFTW3 library is available using pkg-config
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FFTW... yes
FFTW3 found!
checking whether pkg-config knows about libtiff-4... yes
checking for configurable backends... checking whether --static is needed... no
checking for g++ -std=gnu++14 option to support OpenMP... -fopenmp
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/opt/R/4.2.1/lib/R/include" -DNDEBUG  -I/usr/local/include  -Dcimg_use_fftw3  -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/cloud/lib/x86_64-pc-linux-gnu-library/4.2/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/opt/R/4.2.1/lib/R/include" -DNDEBUG  -I/usr/local/include  -Dcimg_use_fftw3  -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/cloud/lib/x86_64-pc-linux-gnu-library/4.2/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c colourspace.cpp -o colourspace.o
g++ -std=gnu++11 -I"/opt/R/4.2.1/lib/R/include" -DNDEBUG  -I/usr/local/include  -Dcimg_use_fftw3  -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/cloud/lib/x86_64-pc-linux-gnu-library/4.2/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c coordinates.cpp -o coordinates.o
g++ -std=gnu++11 -I"/opt/R/4.2.1/lib/R/include" -DNDEBUG  -I/usr/local/include  -Dcimg_use_fftw3  -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/cloud/lib/x86_64-pc-linux-gnu-library/4.2/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c display.cpp -o display.o
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [/opt/R/4.2.1/lib/R/etc/Makeconf:177: display.o] Error 1
ERROR: compilation failed for package ‘imager’
* removing ‘/cloud/lib/x86_64-pc-linux-gnu-library/4.2/imager’

The downloaded source packages are in
	‘/tmp/Rtmpga7T7S/downloaded_packages’
✔  checking for file ‘/tmp/Rtmpga7T7S/remotesf71a42071b/mchizk1-ShinyFruit-bb14698/DESCRIPTION’ ...
─  preparing ‘ShinyFruit’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
   ERROR: dependency ‘imager’ is not available for package ‘ShinyFruit’
─  removing ‘/tmp/RtmpKMT2am/Rinst3ad1887b636/ShinyFruit’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'ShinyFruit' from GitHub:
  ! System command 'R' failed
In addition: Warning message:
In i.p(...) : installation of package ‘imager’ had non-zero exit status

**Comment by mchizk1** [comment]
Sorry to hear that you're having trouble installing, but I appreciate the report!  The most common problems I'm seeing with imager installation have to do with it's X11 dependency.  If you haven't already, you could try downloading or updating XQuartz at https://www.xquartz.org/ .  I'll also say that I haven't tested the app on unix/linux systems yet, so it's quite possible that you could encounter other errors.  I will be devoting some time to this in the next couple weeks.

**Comment by Fema81** [comment]
Hi, thanks for the advice I've fixed the problem. I was finally running the app, however in the control Panel at Step 2 instead of having as option in "Select Variables" RDR, drupelet Count and Size as shown in vignettes I got Color-Based Feature, Color Profile, and Size. Do I miss something?

**Comment by mchizk1** [comment]
Nope!  The pictures reflect the list I had in an earlier version.  I need newer pictures 😄
